# Site settings
title: yyferdinand
header-img: img/home-bg.jpg
email: 1603982241.com
description: "IStyle, IGuitar, IDesign, IShoot, IFE.。@刘艳云的博客主页, 知乎@ 刘艳云／Front-End／Web &amp; Mobile Lover"
baseurl: ""
url: "http://yyferdinand.github.io"
github_username:  ferdinand
facebook_username:  profile.php?id=100008082793376
weibo_username: u/3805959223
zhihu_username: liu-yan-yun-23

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
